// This shader counts the amount of rend pixels in a texture
// Input: Texture
// Output: uint, Number of red pixels in Texture
//
// This is used to make statistics about how efficient the object space shading is (first test).

#pragma kernel Count

Texture2D<float3> Input;
RWStructuredBuffer<uint> Output;

[numthreads(8, 8, 1)]
void Count(uint3 id : SV_DispatchThreadID)
{
	if (Input[id.xy].x == 1) {
		InterlockedAdd(Output[0], 1);
	}
}